[package]
name = "ddisasm-ascent"
version = "0.1.0"
edition = "2021"

[dependencies]
ascent = { path = "./ascent/ascent" }
csv="1.0.0" 
serde="1.0.193"
itertools = "0.13.0"
libc = "0.2.167"

[features]
par = ["ascent/par"]
default = ["par"]
